// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CronJobLocksColumns holds the columns for the "cron_job_locks" table.
	CronJobLocksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "job_name", Type: field.TypeString},
		{Name: "job_identifier", Type: field.TypeString},
		{Name: "worker", Type: field.TypeString},
		{Name: "status", Type: field.TypeString},
	}
	// CronJobLocksTable holds the schema information for the "cron_job_locks" table.
	CronJobLocksTable = &schema.Table{
		Name:       "cron_job_locks",
		Columns:    CronJobLocksColumns,
		PrimaryKey: []*schema.Column{CronJobLocksColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "cronjoblock_job_name_job_identifier",
				Unique:  true,
				Columns: []*schema.Column{CronJobLocksColumns[3], CronJobLocksColumns[4]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CronJobLocksTable,
	}
)

func init() {
}
