// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bbedward/gocron-ent-lock/v2/ent/cronjoblock"
	"github.com/bbedward/gocron-ent-lock/v2/ent/predicate"
)

// CronJobLockQuery is the builder for querying CronJobLock entities.
type CronJobLockQuery struct {
	config
	ctx        *QueryContext
	order      []cronjoblock.OrderOption
	inters     []Interceptor
	predicates []predicate.CronJobLock
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CronJobLockQuery builder.
func (cjlq *CronJobLockQuery) Where(ps ...predicate.CronJobLock) *CronJobLockQuery {
	cjlq.predicates = append(cjlq.predicates, ps...)
	return cjlq
}

// Limit the number of records to be returned by this query.
func (cjlq *CronJobLockQuery) Limit(limit int) *CronJobLockQuery {
	cjlq.ctx.Limit = &limit
	return cjlq
}

// Offset to start from.
func (cjlq *CronJobLockQuery) Offset(offset int) *CronJobLockQuery {
	cjlq.ctx.Offset = &offset
	return cjlq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cjlq *CronJobLockQuery) Unique(unique bool) *CronJobLockQuery {
	cjlq.ctx.Unique = &unique
	return cjlq
}

// Order specifies how the records should be ordered.
func (cjlq *CronJobLockQuery) Order(o ...cronjoblock.OrderOption) *CronJobLockQuery {
	cjlq.order = append(cjlq.order, o...)
	return cjlq
}

// First returns the first CronJobLock entity from the query.
// Returns a *NotFoundError when no CronJobLock was found.
func (cjlq *CronJobLockQuery) First(ctx context.Context) (*CronJobLock, error) {
	nodes, err := cjlq.Limit(1).All(setContextOp(ctx, cjlq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{cronjoblock.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cjlq *CronJobLockQuery) FirstX(ctx context.Context) *CronJobLock {
	node, err := cjlq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CronJobLock ID from the query.
// Returns a *NotFoundError when no CronJobLock ID was found.
func (cjlq *CronJobLockQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cjlq.Limit(1).IDs(setContextOp(ctx, cjlq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{cronjoblock.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cjlq *CronJobLockQuery) FirstIDX(ctx context.Context) int {
	id, err := cjlq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CronJobLock entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CronJobLock entity is found.
// Returns a *NotFoundError when no CronJobLock entities are found.
func (cjlq *CronJobLockQuery) Only(ctx context.Context) (*CronJobLock, error) {
	nodes, err := cjlq.Limit(2).All(setContextOp(ctx, cjlq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{cronjoblock.Label}
	default:
		return nil, &NotSingularError{cronjoblock.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cjlq *CronJobLockQuery) OnlyX(ctx context.Context) *CronJobLock {
	node, err := cjlq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CronJobLock ID in the query.
// Returns a *NotSingularError when more than one CronJobLock ID is found.
// Returns a *NotFoundError when no entities are found.
func (cjlq *CronJobLockQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cjlq.Limit(2).IDs(setContextOp(ctx, cjlq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{cronjoblock.Label}
	default:
		err = &NotSingularError{cronjoblock.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cjlq *CronJobLockQuery) OnlyIDX(ctx context.Context) int {
	id, err := cjlq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CronJobLocks.
func (cjlq *CronJobLockQuery) All(ctx context.Context) ([]*CronJobLock, error) {
	ctx = setContextOp(ctx, cjlq.ctx, ent.OpQueryAll)
	if err := cjlq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CronJobLock, *CronJobLockQuery]()
	return withInterceptors[[]*CronJobLock](ctx, cjlq, qr, cjlq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cjlq *CronJobLockQuery) AllX(ctx context.Context) []*CronJobLock {
	nodes, err := cjlq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CronJobLock IDs.
func (cjlq *CronJobLockQuery) IDs(ctx context.Context) (ids []int, err error) {
	if cjlq.ctx.Unique == nil && cjlq.path != nil {
		cjlq.Unique(true)
	}
	ctx = setContextOp(ctx, cjlq.ctx, ent.OpQueryIDs)
	if err = cjlq.Select(cronjoblock.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cjlq *CronJobLockQuery) IDsX(ctx context.Context) []int {
	ids, err := cjlq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cjlq *CronJobLockQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cjlq.ctx, ent.OpQueryCount)
	if err := cjlq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cjlq, querierCount[*CronJobLockQuery](), cjlq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cjlq *CronJobLockQuery) CountX(ctx context.Context) int {
	count, err := cjlq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cjlq *CronJobLockQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cjlq.ctx, ent.OpQueryExist)
	switch _, err := cjlq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cjlq *CronJobLockQuery) ExistX(ctx context.Context) bool {
	exist, err := cjlq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CronJobLockQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cjlq *CronJobLockQuery) Clone() *CronJobLockQuery {
	if cjlq == nil {
		return nil
	}
	return &CronJobLockQuery{
		config:     cjlq.config,
		ctx:        cjlq.ctx.Clone(),
		order:      append([]cronjoblock.OrderOption{}, cjlq.order...),
		inters:     append([]Interceptor{}, cjlq.inters...),
		predicates: append([]predicate.CronJobLock{}, cjlq.predicates...),
		// clone intermediate query.
		sql:       cjlq.sql.Clone(),
		path:      cjlq.path,
		modifiers: append([]func(*sql.Selector){}, cjlq.modifiers...),
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CronJobLock.Query().
//		GroupBy(cronjoblock.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cjlq *CronJobLockQuery) GroupBy(field string, fields ...string) *CronJobLockGroupBy {
	cjlq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CronJobLockGroupBy{build: cjlq}
	grbuild.flds = &cjlq.ctx.Fields
	grbuild.label = cronjoblock.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.CronJobLock.Query().
//		Select(cronjoblock.FieldCreatedAt).
//		Scan(ctx, &v)
func (cjlq *CronJobLockQuery) Select(fields ...string) *CronJobLockSelect {
	cjlq.ctx.Fields = append(cjlq.ctx.Fields, fields...)
	sbuild := &CronJobLockSelect{CronJobLockQuery: cjlq}
	sbuild.label = cronjoblock.Label
	sbuild.flds, sbuild.scan = &cjlq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CronJobLockSelect configured with the given aggregations.
func (cjlq *CronJobLockQuery) Aggregate(fns ...AggregateFunc) *CronJobLockSelect {
	return cjlq.Select().Aggregate(fns...)
}

func (cjlq *CronJobLockQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cjlq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cjlq); err != nil {
				return err
			}
		}
	}
	for _, f := range cjlq.ctx.Fields {
		if !cronjoblock.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cjlq.path != nil {
		prev, err := cjlq.path(ctx)
		if err != nil {
			return err
		}
		cjlq.sql = prev
	}
	return nil
}

func (cjlq *CronJobLockQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CronJobLock, error) {
	var (
		nodes = []*CronJobLock{}
		_spec = cjlq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CronJobLock).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CronJobLock{config: cjlq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(cjlq.modifiers) > 0 {
		_spec.Modifiers = cjlq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cjlq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (cjlq *CronJobLockQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cjlq.querySpec()
	if len(cjlq.modifiers) > 0 {
		_spec.Modifiers = cjlq.modifiers
	}
	_spec.Node.Columns = cjlq.ctx.Fields
	if len(cjlq.ctx.Fields) > 0 {
		_spec.Unique = cjlq.ctx.Unique != nil && *cjlq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cjlq.driver, _spec)
}

func (cjlq *CronJobLockQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(cronjoblock.Table, cronjoblock.Columns, sqlgraph.NewFieldSpec(cronjoblock.FieldID, field.TypeInt))
	_spec.From = cjlq.sql
	if unique := cjlq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cjlq.path != nil {
		_spec.Unique = true
	}
	if fields := cjlq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cronjoblock.FieldID)
		for i := range fields {
			if fields[i] != cronjoblock.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cjlq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cjlq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cjlq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cjlq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cjlq *CronJobLockQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cjlq.driver.Dialect())
	t1 := builder.Table(cronjoblock.Table)
	columns := cjlq.ctx.Fields
	if len(columns) == 0 {
		columns = cronjoblock.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cjlq.sql != nil {
		selector = cjlq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cjlq.ctx.Unique != nil && *cjlq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range cjlq.modifiers {
		m(selector)
	}
	for _, p := range cjlq.predicates {
		p(selector)
	}
	for _, p := range cjlq.order {
		p(selector)
	}
	if offset := cjlq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cjlq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (cjlq *CronJobLockQuery) Modify(modifiers ...func(s *sql.Selector)) *CronJobLockSelect {
	cjlq.modifiers = append(cjlq.modifiers, modifiers...)
	return cjlq.Select()
}

// CronJobLockGroupBy is the group-by builder for CronJobLock entities.
type CronJobLockGroupBy struct {
	selector
	build *CronJobLockQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cjlgb *CronJobLockGroupBy) Aggregate(fns ...AggregateFunc) *CronJobLockGroupBy {
	cjlgb.fns = append(cjlgb.fns, fns...)
	return cjlgb
}

// Scan applies the selector query and scans the result into the given value.
func (cjlgb *CronJobLockGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cjlgb.build.ctx, ent.OpQueryGroupBy)
	if err := cjlgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CronJobLockQuery, *CronJobLockGroupBy](ctx, cjlgb.build, cjlgb, cjlgb.build.inters, v)
}

func (cjlgb *CronJobLockGroupBy) sqlScan(ctx context.Context, root *CronJobLockQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cjlgb.fns))
	for _, fn := range cjlgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cjlgb.flds)+len(cjlgb.fns))
		for _, f := range *cjlgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cjlgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cjlgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CronJobLockSelect is the builder for selecting fields of CronJobLock entities.
type CronJobLockSelect struct {
	*CronJobLockQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cjls *CronJobLockSelect) Aggregate(fns ...AggregateFunc) *CronJobLockSelect {
	cjls.fns = append(cjls.fns, fns...)
	return cjls
}

// Scan applies the selector query and scans the result into the given value.
func (cjls *CronJobLockSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cjls.ctx, ent.OpQuerySelect)
	if err := cjls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CronJobLockQuery, *CronJobLockSelect](ctx, cjls.CronJobLockQuery, cjls, cjls.inters, v)
}

func (cjls *CronJobLockSelect) sqlScan(ctx context.Context, root *CronJobLockQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cjls.fns))
	for _, fn := range cjls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cjls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cjls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (cjls *CronJobLockSelect) Modify(modifiers ...func(s *sql.Selector)) *CronJobLockSelect {
	cjls.modifiers = append(cjls.modifiers, modifiers...)
	return cjls
}
