// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bbedward/gocron-ent-lock/v2/ent/cronjoblock"
	"github.com/bbedward/gocron-ent-lock/v2/ent/predicate"
)

// CronJobLockDelete is the builder for deleting a CronJobLock entity.
type CronJobLockDelete struct {
	config
	hooks    []Hook
	mutation *CronJobLockMutation
}

// Where appends a list predicates to the CronJobLockDelete builder.
func (cjld *CronJobLockDelete) Where(ps ...predicate.CronJobLock) *CronJobLockDelete {
	cjld.mutation.Where(ps...)
	return cjld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cjld *CronJobLockDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, cjld.sqlExec, cjld.mutation, cjld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (cjld *CronJobLockDelete) ExecX(ctx context.Context) int {
	n, err := cjld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cjld *CronJobLockDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(cronjoblock.Table, sqlgraph.NewFieldSpec(cronjoblock.FieldID, field.TypeInt))
	if ps := cjld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cjld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	cjld.mutation.done = true
	return affected, err
}

// CronJobLockDeleteOne is the builder for deleting a single CronJobLock entity.
type CronJobLockDeleteOne struct {
	cjld *CronJobLockDelete
}

// Where appends a list predicates to the CronJobLockDelete builder.
func (cjldo *CronJobLockDeleteOne) Where(ps ...predicate.CronJobLock) *CronJobLockDeleteOne {
	cjldo.cjld.mutation.Where(ps...)
	return cjldo
}

// Exec executes the deletion query.
func (cjldo *CronJobLockDeleteOne) Exec(ctx context.Context) error {
	n, err := cjldo.cjld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{cronjoblock.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cjldo *CronJobLockDeleteOne) ExecX(ctx context.Context) {
	if err := cjldo.Exec(ctx); err != nil {
		panic(err)
	}
}
