// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/bbedward/gocron-ent-lock/v2/ent/cronjoblock"
	"github.com/bbedward/gocron-ent-lock/v2/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	cronjoblockFields := schema.CronJobLock{}.Fields()
	_ = cronjoblockFields
	// cronjoblockDescCreatedAt is the schema descriptor for created_at field.
	cronjoblockDescCreatedAt := cronjoblockFields[1].Descriptor()
	// cronjoblock.DefaultCreatedAt holds the default value on creation for the created_at field.
	cronjoblock.DefaultCreatedAt = cronjoblockDescCreatedAt.Default.(func() time.Time)
	// cronjoblockDescUpdatedAt is the schema descriptor for updated_at field.
	cronjoblockDescUpdatedAt := cronjoblockFields[2].Descriptor()
	// cronjoblock.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	cronjoblock.DefaultUpdatedAt = cronjoblockDescUpdatedAt.Default.(func() time.Time)
	// cronjoblock.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	cronjoblock.UpdateDefaultUpdatedAt = cronjoblockDescUpdatedAt.UpdateDefault.(func() time.Time)
	// cronjoblockDescJobName is the schema descriptor for job_name field.
	cronjoblockDescJobName := cronjoblockFields[3].Descriptor()
	// cronjoblock.JobNameValidator is a validator for the "job_name" field. It is called by the builders before save.
	cronjoblock.JobNameValidator = cronjoblockDescJobName.Validators[0].(func(string) error)
	// cronjoblockDescJobIdentifier is the schema descriptor for job_identifier field.
	cronjoblockDescJobIdentifier := cronjoblockFields[4].Descriptor()
	// cronjoblock.JobIdentifierValidator is a validator for the "job_identifier" field. It is called by the builders before save.
	cronjoblock.JobIdentifierValidator = cronjoblockDescJobIdentifier.Validators[0].(func(string) error)
	// cronjoblockDescWorker is the schema descriptor for worker field.
	cronjoblockDescWorker := cronjoblockFields[5].Descriptor()
	// cronjoblock.WorkerValidator is a validator for the "worker" field. It is called by the builders before save.
	cronjoblock.WorkerValidator = cronjoblockDescWorker.Validators[0].(func(string) error)
	// cronjoblockDescStatus is the schema descriptor for status field.
	cronjoblockDescStatus := cronjoblockFields[6].Descriptor()
	// cronjoblock.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	cronjoblock.StatusValidator = cronjoblockDescStatus.Validators[0].(func(string) error)
	// cronjoblockDescID is the schema descriptor for id field.
	cronjoblockDescID := cronjoblockFields[0].Descriptor()
	// cronjoblock.IDValidator is a validator for the "id" field. It is called by the builders before save.
	cronjoblock.IDValidator = cronjoblockDescID.Validators[0].(func(int) error)
}
