// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CronJobLock is the predicate function for cronjoblock builders.
type CronJobLock func(*sql.Selector)
